### ISSUE TITLE
Installation step 1 via pip install issues

### ISSUE THREAD

**Issue by HoloDirk** [buaacyw/GaussianEditor#17]
Hello all,

I am running a win 11 pro computer with rtx 4090, using conda cmd prompt.

I have tried all 3 options for installation. Any help to resolve below issues greatly appreciated.

Step 1, option 2 pip install gets me the closest via # CUDA version 11.8 -

(base) C:\Users\Dirk\GaussianEditor>pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
NO errors.

(base) C:\Users\Dirk\GaussianEditor>pip install -r requirements.txt
Errors below-

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Dirk\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\Dirk\anaconda3\Lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dirk\anaconda3\Lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dirk\anaconda3\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Dirk\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dirk\anaconda3\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

**Comment by iceiilin** [comment]
Same here. Does anyone have a clue about it?

**Comment by onevfall** [comment]
> Same here. Does anyone have a clue about it?
Same here too. Do you have any solution now?

**Comment by onevfall** [comment]
Same here too. Do you have any solution now? @iceiilin
