### ISSUE TITLE
Could not recognize scene type!

### ISSUE THREAD

**Issue by csycvtsbcsbbbycsb** [buaacyw/GaussianEditor#47]
(base) root@autodl-container-f31b4fbcca-d56efb7e:~# python autodl-tmp/GaussianEditor-master/webui.py\
>     --colmap_dir autodl-tmp/GaussianEditor-master/dataset/bicycle \
>     --gs_source autodl-tmp/GaussianEditor-master/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply
/root/miniconda3/lib/python3.8/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
/root/miniconda3/lib/python3.8/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/root/miniconda3/lib/python3.8/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/root/miniconda3/lib/python3.8/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/root/miniconda3/lib/python3.8/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/root/miniconda3/lib/python3.8/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
Traceback (most recent call last):
  File "autodl-tmp/GaussianEditor-master/webui.py", line 1569, in <module>
    webui = WebUI(args)
  File "autodl-tmp/GaussianEditor-master/webui.py", line 129, in __init__
    scene = CamScene(self.colmap_dir, h=512, w=512)
  File "/root/autodl-tmp/GaussianEditor-master/gaussiansplatting/scene/camera_scene.py", line 39, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

**Comment by yoyoNTNU** [comment]
you can refer to https://github.com/buaacyw/GaussianEditor/issues/3
