### ISSUE TITLE
Error about No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by luzhiyuan25** [buaacyw/GaussianEditor#74]
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      /tmp/pip-install-sodnkdq4/numba_d889e220927d44fb9b293c4cf1a44f7d/setup.py:13: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        import numpy.distutils.misc_util as np_misc
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-sodnkdq4/numba_d889e220927d44fb9b293c4cf1a44f7d/setup.py", line 25, in <module>
          'long_description': open('README.rst').read(),
      FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kitano-kazuki** [comment]
Exactly the same error, when doing `conda env create -f environment.yaml`

**Comment by luzhiyuan25** [comment]
> Exactly the same error, when doing `conda env create -f environment.yaml`

# (Option three) If the below two options fail, please try this:
# For CUDA 11.8
bash install.sh

I dont know Option two is useful or not.
