### ISSUE TITLE
KeyError: 'vit_h'

### ISSUE THREAD

**Issue by LiYifan985** [buaacyw/GaussianEditor#79]
F:\GS+\fenge\GaussianEditor\segment-anything-2\sam2\modeling\sam\transformer.py:23: UserWarning: You are using PyTorch 2.0.1+cu117 without Flash Attention v2 support. Consider upgrading to PyTorch 2.2+ for Flash Attention v2 (which could be faster).
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
Reading camera 53/53
Traceback (most recent call last):
  File "F:\GS+\fenge\GaussianEditor\webui.py", line 1569, in <module>
    webui = WebUI(args)
  File "F:\GS+\fenge\GaussianEditor\webui.py", line 139, in __init__
    self.text_segmentor = LangSAMTextSegmentor().to(get_device())
  File "F:\GS+\fenge\GaussianEditor\threestudio\utils\sam.py", line 17, in __init__
    self.model = LangSAM(sam_type)
  File "F:\GS+\fenge\GaussianEditor\lang-segment-anything\lang_sam\lang_sam.py", line 12, in __init__
    self.sam.build_model(sam_type, ckpt_path)
  File "F:\GS+\fenge\GaussianEditor\lang-segment-anything\lang_sam\models\sam.py", line 44, in build_model
    cfg = compose(config_name=SAM_MODELS[self.sam_type]["config"], overrides=[])
KeyError: 'vit_h'

**Comment by StardustandRain** [comment]
我也遇到了同样的问题 请问您解决了吗

**Comment by LiYifan985** [comment]
> 我也遇到了同样的问题 请问您解决了吗
你定位到源代码，有一个名称引用要更改，具体位置我忘了，在pycharm控制台运行根据报错位置找

**Comment by zhurui1995** [comment]
yeah, you can change "vit_h" to "sam2.1_hiera_large", it works for me.

threestudio/utils/sam.py
````python
# line 15 
# def __init__(self, sam_type="vit_h"):
def __init__(self, sam_type="sam2.1_hiera_large"):
```
